### ISSUE TITLE
[Bug]: Firmware reset after battery dies

### ISSUE THREAD

**Issue by DomTheDorito** [meshtastic/firmware#3260]
### Category

Other

### Hardware

Heltec v2

### Firmware Version

2.2.21

### Description

Device settings get reset after battery dies (region, channels, users etc). 

To reproduce issue:

1. While device is powered on, allow battery to run flat
2. Plug in the charge battery/power device
3. Region becomes unset, and acts like its a new device, asks to re-pair to phone

**Comment by pdxlocations** [comment]
I'm curious, Is the node connected to a client by Bluetooth when the battery dies? Does it reset when NOT connected via Bluetooth?

**Comment by DomTheDorito** [comment]
It's done it in both cases now.

**Comment by pdxlocations** [comment]
Ok thanks, I had a brownout reset issue with nRF and others have reported resets when losing Bluetooth connection so I was curious if they might me related. #2936

**Comment by DomTheDorito** [comment]
I'll do some more testing tomorrow afternoon, and I'll try and get some useful logs

**Comment by Hamspiced** [comment]
Same issue, rak 4631 with a 1000mah flat pack.

When mine resets though the ble pin switches to random and I have to reset via serial

**Comment by cracky22** [comment]
same issue with my heltec v2.1....

**Comment by OrByR** [comment]
I have run into this issue at least once on a Heltec v3 as well.

**Comment by Holyszewski** [comment]
In my case, on a Heltec v3 set up as a router, the brownout just resets the long and short name. The other settings seem to be preserved and it allows me to fix the name settings remotely via the admin channel.

FW 2.3.2 I believe.

**Comment by cracky22** [comment]
Yep and finally my heltec v3 now also has these problems

**Comment by Hamspiced** [comment]
> Does this happen every time the battery dies, or just sometimes?

It is infrequent.  Sometimes ill go 2-3 charges from dead before it pops up.  Sometimes a week.

The Heltec Wireless Stick Lite seems to have it happen much more frequently than my other devices.

Recently a solar node/rak wireless build had this occur.  Normally not an issue but it was mounted 30' up.  Definately a pita to get it down and set it up again.  This particular device was setup as a Router/Client  the other devices i had it occur on were only clients.

**Comment by cracky22** [comment]
> Does this happen every time the battery dies, or just sometimes?

For me the problem only occurs very sporadically. sometimes it can take weeks to occur but sometimes three to four days are enough...

**Comment by WUBBSY** [comment]
> In my case, on a Heltec v3 set up as a router, the brownout just resets the long and short name. The other settings seem to be preserved and it allows me to fix the name settings remotely via the admin channel.
> 
> 
> 
> FW 2.3.2 I believe. 

Had the same issue on both my Heltec Tracker nodes after the battery went flat. 
Set up as Clients. 
FW 2.3.3

**Comment by fattredd** [comment]
I'm also seeing the same on 2.3.10 on Heltec V3. Set up as Router Clients.

**Comment by cliffjao** [comment]
I'm running into this issue on rak4631 but battery is still solid at 95%.

**Comment by tedwardd** [comment]
Still seems to be an issue with the Heltec V3 using 2.5.0.e470619 preview. All settings lost after battery depletion. Perhaps a "safe shutdown" feature would be a reasonable stop-gap solution here. Similar to power off on power loss but "power off at X percentage battery remaining"?

**Comment by droptic** [comment]
Same problem in lora32 v2.1_1.6

**Comment by dannypagano** [comment]
Same issue with my Heltev V3 on 2.4.2. All settings lost after battery runs flat. Wants to re-pair, region is reset, heartbeat LED setting resets, channels lost, etc. On iOS, the Meshtastic app still sees the device via bluetooth, but fails to automatically reconnect, and requires you to forget the bluetooth device and re-pair. 

It's happened every single time the battery runs flat (~10-12 hours 🫠). Always connected to the phone via bluetooth when the battery dies.

I have another identical device that I'll test to see if the same issue persists.

**Comment by CyberRatingsTim** [comment]
Same on Heltec v3 based on the ESP32 i think. 
Every time the battery dies all the way, it loses settings and acts like a new device to pair with.

**Comment by CyberRatingsTim** [comment]
before 2.49V it goes into a boot loop. and loses the settings

**Comment by cracky22** [comment]
I’m now at the point where the problem occurs daily on my Heltec V3 and V2 (I know that the V2 is no longer supported) when the battery drops below ~40%. This is quite frustrating! As a V2 user, is there still a way for me to fix this issue on my V2 board once the bug is resolved, considering that the update files are no longer provided via GitHub release files?

**Comment by adingbatponder** [comment]
https://github.com/orgs/meshtastic/discussions/5#discussion-7387496

**Comment by fifieldt** [comment]
Did anyone see an improvement after using 2.5.10 or 2.5.11 ? There were some filesystem related changes.

**Comment by cracky22** [comment]
> Did anyone see an improvement after using 2.5.10 or 2.5.11 ? There were some filesystem related changes.

Hi, I haven't seen anything spontaneously yet but I can only run my devices with battery and observe

**Comment by cracky22** [comment]
> Did anyone see an improvement after using 2.5.10 or 2.5.11 ? There were some filesystem related changes.

Good morning, the bug seems to have been fixed on my devices. I've drained them twice and all the data is still there. Great work!
I have another question: Can I now fix THIS bug on the no longer supported Heltec v2.1 models ?

**Comment by fifieldt** [comment]
Drop by #firmware on discord and I'm sure someone will be happy to build a firmware for you :)

**Comment by fifieldt** [comment]
Closing this one since it appears to be fixed. We're still working on the related one here: https://github.com/meshtastic/firmware/issues/4555

**Comment by varna9000** [comment]
I'm sorry to resurrect this but I see the same settings reset on seeed xiao nrf52840. I've tested the latest stable 2.6.11 and all 2.7.x alfas as well. It happened to 4 different xiao nrf52840 solar nodes with batteries. However the batteries are not getting flat as they had around 80% charge when the node was last seen.

**Comment by brunoarine** [comment]
I've just observed this behavior on a Heltec V4, so definitely not solved.

**Comment by varna9000** [comment]
> I've just observed this behavior on a Heltec V4, so definitely not solved.

I'm suspecting high current spikes when LoRa radio is working, which leads to brownout when node is writing to flash. I'm now experimenting with adding 100uF cap between 3.3v and Gnd on the microcontroller pins, which could smooth out some of these spike. Let's see if this fixes the issue.

**Comment by bittylicious** [comment]
Like @brunoarine I've just noticed this with my Heltec v4. It was connected to a 3000mah battery which died, and I lost all settings.
